// Synthetic fixtures: original IronClad test artwork/audio, CC0-1.0.
// Uses the installed browser's native WebCodecs encoder and the pinned JS muxer.
// No FFmpeg, native server codec library, network media or external source footage.
import { chromium } from "@playwright/test";
import { createServer } from "node:http";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
const directory = dirname(fileURLToPath(import.meta.url));
const bundle = await readFile(resolve(directory, "../../../node_modules/mediabunny/dist/bundles/mediabunny.mjs"));
const server = createServer((req, res) => {
  res.setHeader("Content-Type", req.url === "/bundle.mjs" ? "text/javascript" : "text/html");
  res.end(req.url === "/bundle.mjs" ? bundle : "<!doctype html><title>Synthetic media fixture encoder</title>");
});
await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
let browser;
try {
  browser = await chromium.launch({ headless: true, channel: "chrome" });
  const page = await browser.newPage();
  await page.goto("http://127.0.0.1:" + server.address().port);
  const browserVersion = await browser.version();
  const specs = [

    { name: "synthetic-vp8-opus.webm", codec: "vp8", audio: "opus", width: 320, height: 180, fps: 30, frames: 30 },
    { name: "synthetic-vp9-opus.webm", codec: "vp9", audio: "opus", width: 320, height: 180, fps: 30, frames: 30 },
    { name: "synthetic-avc-silent.mp4", codec: "avc", audio: null, width: 320, height: 180, fps: 60, frames: 60 },
    { name: "synthetic-vp9-silent.webm", codec: "vp9", audio: null, width: 320, height: 180, fps: 60, frames: 60 },
    { name: "synthetic-avc-1080p.mp4", codec: "avc", audio: null, width: 1920, height: 1080, fps: 30, frames: 3 },
    { name: "synthetic-avc-oversize.mp4", codec: "avc", audio: null, width: 1922, height: 1080, fps: 30, frames: 3 },
  ];
  const manifest = { license: "CC0-1.0", source: "Original synthetic colored rectangles and a 440 Hz sine wave; generated by generate.mjs.", browserVersion, encoder: "Chrome native WebCodecs", muxer: "mediabunny@1.56.2", files: [] };
  for (const spec of specs) {
    const result = await page.evaluate(async spec => {
      const M = await import("/bundle.mjs");
      const canvas = new OffscreenCanvas(spec.width, spec.height);
      const context = canvas.getContext("2d");
      const output = new M.Output({ format: spec.codec === "avc" ? new M.Mp4OutputFormat({ fastStart: "in-memory" }) : new M.WebMOutputFormat(), target: new M.BufferTarget() });
      const video = new M.CanvasSource(canvas, { codec: spec.codec, bitrate: 500_000, keyFrameInterval: 0.25 });
      output.addVideoTrack(video, { frameRate: spec.fps });
      let audio;
      if (spec.audio) { audio = new M.AudioSampleSource({ codec: spec.audio, bitrate: 64_000 }); output.addAudioTrack(audio); }
      await output.start();
      for (let i = 0; i < spec.frames; i++) {
        context.fillStyle = i % 2 ? "#183549" : "#26301c";
        context.fillRect(0, 0, spec.width, spec.height);
        context.fillStyle = "#eb6b17";
        context.fillRect(i % 20 * 5, 10, 40, 30);
        await video.add(i / spec.fps, 1 / spec.fps);
      }
      if (audio) {
        const values = new Float32Array(Math.round(spec.frames / spec.fps * 48000));
        for (let i = 0; i < values.length; i++) values[i] = Math.sin(i / 48000 * 2 * Math.PI * 440) * 0.1;
        const sample = new M.AudioSample({ data: values, format: "f32-planar", sampleRate: 48000, numberOfChannels: 1, timestamp: 0 });
        await audio.add(sample); sample.close();
      }
      await output.finalize();
      const bytes = new Uint8Array(output.target.buffer);
      return Array.from(bytes);
    }, spec);
    const bytes = Buffer.from(result);
    await writeFile(resolve(directory, spec.name), bytes);
    manifest.files.push({ ...spec, byteLength: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") });
    console.log(spec.name + " " + bytes.length + " bytes");
  }
  await mkdir(directory, { recursive: true });
  await writeFile(resolve(directory, "provenance.json"), JSON.stringify(manifest, null, 2) + "\n");
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
}
